version: "2"
services:
    back:
        build: /server/.
        container_name: news_server
        ports:
          - 5008:5008
        networks:
          network:
            ipv4_address: 10.5.0.2

    front:
        build: /client/.
        container_name: news_client
        ports:
          - 5111:5111
        networks:
          network:
            ipv4_address: 10.5.0.3

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1